apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "18"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"distcc"},"name":"distcc","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"distcc"}},"template":{"metadata":{"labels":{"app":"distcc"}},"spec":{"containers":[{"args":["--no-fork","--no-detach","--allow=0.0.0.0/0","--log-stderr","--verbose"],"image":"ghcr.io/felipedbene/distcc:latest","imagePullPolicy":"Always","name":"distcc","ports":[{"containerPort":3632}],"resources":{"requests":{"cpu":"100m","memory":"128Mi"}}}],"imagePullSecrets":[{"name":"ghcr-creds"}],"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","operator":"Exists"}]}}}}
  creationTimestamp: "2025-05-13T02:21:58Z"
  generation: 18
  labels:
    app: distcc
  name: distcc
  namespace: default
  resourceVersion: "17718588"
  uid: 62ce618c-9317-443e-b87a-4fd02340525a
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-13T21:36:22-05:00"
      creationTimestamp: null
      labels:
        app: distcc
    spec:
      containers:
      - args:
        - --no-fork
        - --no-detach
        - --allow=0.0.0.0/0
        - --log-stderr
        - --verbose
        image: ghcr.io/felipedbene/distcc:latest
        imagePullPolicy: Always
        name: distcc
        ports:
        - containerPort: 3632
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-creds
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberAvailable: 4
  numberMisscheduled: 1
  numberReady: 4
  observedGeneration: 18
  updatedNumberScheduled: 4
